// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj4dRLaErf6YDE50LvvWdUKREqh2BnPpM',
    appId: '1:741908133130:web:7b36acb026ab363ff0f6f3',
    messagingSenderId: '741908133130',
    projectId: 'flutterexample-1b',
    authDomain: 'flutterexample-1b.firebaseapp.com',
    storageBucket: 'flutterexample-1b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPMbuLBpP6OMZ1tQV9vvAEulIptTLWTSo',
    appId: '1:741908133130:android:b59cb80f94c93bc8f0f6f3',
    messagingSenderId: '741908133130',
    projectId: 'flutterexample-1b',
    storageBucket: 'flutterexample-1b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO1g_wTEu8Anfdb3aJpnt4DWHQGEnE9kA',
    appId: '1:741908133130:ios:159af579c897afc8f0f6f3',
    messagingSenderId: '741908133130',
    projectId: 'flutterexample-1b',
    storageBucket: 'flutterexample-1b.appspot.com',
    iosBundleId: 'com.example.firebaselesson',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBO1g_wTEu8Anfdb3aJpnt4DWHQGEnE9kA',
    appId: '1:741908133130:ios:4e3fe167ba863e4af0f6f3',
    messagingSenderId: '741908133130',
    projectId: 'flutterexample-1b',
    storageBucket: 'flutterexample-1b.appspot.com',
    iosBundleId: 'com.example.firebaselesson.RunnerTests',
  );
}
